### ISSUE TITLE
Unable to install tsduck on Big Sur

### ISSUE THREAD

**Issue by rinaldomerlo** [tsduck/homebrew-tsduck#4]
==> Formula
Tap: tsduck/tsduck
Path: /usr/local/Homebrew/Library/Taps/tsduck/homebrew-tsduck/tsduck.rb
==> Configuration
HOMEBREW_VERSION: 3.2.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4e6919b73444e9f9e02ad81d8afc4bbd97533567
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 38a9de8aaccbe51b52cb5d944387331534420f63
Core tap last commit: 50 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
/usr/bin/curl --version
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/openjdk:/usr/local/opt/openssl@1.1:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/cjson/lib/pkgconfig:/usr/local/opt/cmocka/lib/pkgconfig:/usr/local/opt/librist/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/srt/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/dos2unix/bin:/usr/local/opt/gnu-sed/bin:/usr/local/opt/grep/bin:/usr/local/opt/openjdk/bin:/usr/local/opt/mbedtls/bin:/usr/local/opt/librist/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/srt/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: tsduck/tsduck/tsduck 3.28-2551 did not build
Logs:
     /Users/rmerlo/Library/Logs/Homebrew/tsduck/01.make
     /Users/rmerlo/Library/Logs/Homebrew/tsduck/00.options.out
     /Users/rmerlo/Library/Logs/Homebrew/tsduck/01.make.cc
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/tsduck/homebrew-tsduck/issues

/usr/bin/curl --disable --cookie-jar /dev/null --globoff --show-error --user-agent Homebrew/3.2.14\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.6\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=tsduck\+repo\%3Atsduck\%2Fhomebrew-tsduck\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --dump-header /private/tmp/github_api_headers20211005-32179-1k0o75j
rmerlo@RMERLO1M-REM2 temp 
[tsduck.zip](https://github.com/tsduck/homebrew-tsduck/files/7284792/tsduck.zip)
%

**Comment by rinaldomerlo** [comment]
rmerlo@RMERLO1M-REM2 temp % brew install  tsduck                 
Updating Homebrew...
==> Downloading https://github.com/tsduck/tsduck/archive/v3.28-2551.tar.gz
Already downloaded: /Users/rmerlo/Library/Caches/Homebrew/downloads/d054c5ea6ba37b65ce18f663f79ab20e9f77b80c7b48ade841624c49ebcbac16--tsduck-3.28-2551.tar.gz
==> Installing tsduck from tsduck/tsduck
==> make NOGITHUB=1 NOTEST=1
Last 15 lines from /Users/rmerlo/Library/Logs/Homebrew/tsduck/01.make:
1 error generated.
make[2]: *** [/private/tmp/tsduck-20211005-38877-s1e9qd/tsduck-3.28-2551/bin/release-x86_64-RMERLO1M-REM2/objs-libtsduck/tsAACDescriptor.o] Error 1
make[2]: *** [/private/tmp/tsduck-20211005-38877-s1e9qd/tsduck-3.28-2551/bin/release-x86_64-RMERLO1M-REM2/objs-libtsduck/tsAES.o] Error 1
1 error generated.
make[2]: *** [/private/tmp/tsduck-20211005-38877-s1e9qd/tsduck-3.28-2551/bin/release-x86_64-RMERLO1M-REM2/objs-libtsduck/tsARIBCharset.o] Error 1
1 error generated.
make[2]: *** [/private/tmp/tsduck-20211005-38877-s1e9qd/tsduck-3.28-2551/bin/release-x86_64-RMERLO1M-REM2/objs-libtsduck/tsARIBCharsetData.o] Error 1
1 error generated.
make[2]: *** [/private/tmp/tsduck-20211005-38877-s1e9qd/tsduck-3.28-2551/bin/release-x86_64-RMERLO1M-REM2/objs-libtsduck/tsAFExtensionsDescriptor.o] Error 1
1 error generated.
make[2]: *** [/private/tmp/tsduck-20211005-38877-s1e9qd/tsduck-3.28-2551/bin/release-x86_64-RMERLO1M-REM2/objs-libtsduck/tsARIBCharsetEncoding.o] Error 1
1 error generated.
make[2]: *** [/private/tmp/tsduck-20211005-38877-s1e9qd/tsduck-3.28-2551/bin/release-x86_64-RMERLO1M-REM2/objs-libtsduck/tsAIT.o] Error 1
make[1]: *** [default] Error 2
make: *** [default] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/tsduck/homebrew-tsduck/issues

These open issues may also help:
Unable to install tsduck on Big Sur https://github.com/tsduck/homebrew-tsduck/issues/4
rmerlo@RMERLO1M-REM2 temp %

**Comment by lelegard** [comment]
Sorry about that. Please use `brew install --HEAD tsduck`.

**Comment by rinaldomerlo** [comment]
Thanks, that has worked.
