### ISSUE TITLE
Brew installation fails on OSX 11.4 Big Sur

### ISSUE THREAD

**Issue by devenreilly** [tsduck/homebrew-tsduck#5]
`Installing tsduck from tsduck/tsduck
Warning: No available formula with the name "librist" (dependency of tsduck/tsduck/tsduck). Did you mean librest, libplist, libpst, libvirt or librcsc?`

**Comment by lelegard** [comment]
Hi @devenreilly 

Try to run `brew update` first, `librist` has been added to Homebrew last month, around mid-September. If your cache is outdated, it may miss it. 

From my masOS 11.6 system:
~~~
$ brew info librist
librist: stable 0.2.6 (bottled), HEAD
Reliable Internet Stream Transport (RIST)
https://code.videolan.org/rist/
/usr/local/Cellar/librist/0.2.6 (20 files, 753.5KB) *
  Built from source on 2021-09-13 at 19:22:25
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/librist.rb
License: BSD-2-Clause
~~~

**Comment by devenreilly** [comment]
> Try to run `brew update` first, `librist` has been added to Homebrew last month, around mid-September. If your cache is outdated, it may miss it.

That solved the issue thanks :)
